{% set name = "ampl-mp" %}
{% set version = "20141208" %}
{% set sha256 = "07244d82dd10738090914d608198172b5bd5b7b05544085a3a36cd477573bd63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/ampl/mp/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - cmake

test:
  files:
    - miniampl

about:
  home: http://ampl.github.io
  license: HPND
  license_file: LICENSE.rst
  summary: 'An open-source library for mathematical programming.'
  description: |
    Reusable high-performance .nl file reader which is up to 6x faster than
    the one provided by ASL
  doc_url: http://ampl.github.io
  dev_url: https://github.com/ampl/mp

extra:
  recipe-maintainers:
    - pstjohn
